parameters:
#    markup_job_queue.example.class: Markup\JobQueueBundle\Example

services:
    markup_admin_job_queue_manager:
        class: Markup\JobQueueBundle\Service\JobManager
        arguments:
            - @bcc_resque.resque
    jobby:
        alias: markup_admin_job_queue_manager
    markup_admin_job_queue_recurring_console_command_reader:
        class: Markup\JobQueueBundle\Service\RecurringConsoleCommandReader
        arguments:
            - %kernel.root_dir%
    markup_admin_job_queue.supervisord_config_file.writer:
        class: Markup\JobQueueBundle\Service\SupervisordConfigFileWriter
        arguments:
            - @logger
            - @jobby
            - %kernel.root_dir%
            - %bcc_resque.prefix%
            - %redis_host%
            - %redis_port%
            - %redis_db%