parameters:
#    markup_job_queue.example.class: Markup\Bundle\JobQueueBundle\Example

services:
    markup_admin_job_queue_manager:
        class: Markup\Bundle\JobQueueBundle\Service\JobManager
        arguments:
            - @bcc_resque.resque
    jobby:
        alias: markup_admin_job_queue_manager
    markup_admin_job_queue_recurring_console_command_reader:
        class: Markup\Bundle\JobQueueBundle\Service\RecurringConsoleCommandReader
        arguments:
            - %kernel.root_dir%